In [8]:
import cv2

# read an image and get the numpy array, pass 0 for grey scale and 1 for getting bgr combination
im_g = cv2.imread("../resources/original.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [9]:
# im_g = cv2.imread("../resources/original.png", 1)
# im_g

In [7]:
# Write an image from numpy array
cv2.imwrite("new_original.png", im_g)

True

In [12]:
# Indexing a numpy array, first position is row and the second position is column. here we have specified range of rows 
# and columns
im_g[0:3, 2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [13]:
im_g[2,4] # Prints the last element

182

In [14]:
# Iterating a numpy array. 
# This prints the entire rows one by one. each row is an array here
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [15]:
# For iterating columns, we need to iterate the transpose of the numpy array
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [19]:
# Stacking 2 numpy arrays: Remember the numpy arrays have to be of the same dimension
# hstack -> Horizontal stack
# vstack -> vertical stack
import numpy
imh = numpy.hstack((im_g, im_g))
print(imh)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [21]:
imv = numpy.vstack((im_g, im_g))
print(imv)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [28]:
# Split numpy arrays into smaller arrays.
# vertical split and horizontal split

ims_h = numpy.hsplit(imh, 2)
print(ims_h)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]


In [30]:
ims_v = numpy.vsplit(imv, 2)
print(ims_v)

[array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8), array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)]
